El *broadcasting* es una técnica que permite realizar operaciones de *cada valor* de una matriz, con *otro número calculado a raíz de la misma matriz*. Por ejemplo, la suma de los valores de las columnas. Lo cual permitiría sacar un promedio.

In [1]:
import numpy as np

A = np.array([[56, 0, 4.4, 68], 
              [1.2, 104, 52, 8],
              [1.8, 135, 99, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
# Suma vertical de la matriz (a lo largo de las columnas)
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [9]:
# Reshape para poder operar con cada valor de la matriz de 4x3
cal = cal.reshape(1,4)
cal

array([[ 59. , 239. , 155.4,  76.9]])

In [10]:
percentage = 100*A/cal
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])