In [1]:
import numpy as np

#### Potenciales errores trabajando con arrays

In [4]:
a = np.random.randn(5) # Crea array de 5 elementos aleatorios de distribución normal
print("Tipo de dato: ", a.dtype)
print("Shape: ", a.shape)
a

Tipo de dato:  float64
Shape:  (5,)


array([ 0.84181865, -1.50178156,  2.06881857, -0.79262136,  1.45637294])

In [6]:
"""Notar que a es un vector de 5 elementos, no es un vector fila o columna, 
    por lo que no se puede hacer operaciones de matriz con él."""
a.T  # Esto no dará error, pero no es lo que se espera, no obtenemos el vector transpuesto

array([ 0.84181865, -1.50178156,  2.06881857, -0.79262136,  1.45637294])

In [7]:
# Por lo dicho anteriormente, esto no tendrá como resultado un vector, sino un escalar.
np.dot(a, a.T)

9.993287529116161

#### Estructura correcta de un vector

In [8]:
# Notar que ahora sí estamos obteniendo un vector columna, por lo que podemos hacer operaciones de matriz con él.
b = np.random.randn(5, 1)
print("Tipo de dato: ", b.dtype)
print("Shape: ", b.shape)
b

Tipo de dato:  float64
Shape:  (5, 1)


array([[-0.60315309],
       [-1.11081319],
       [ 0.09742518],
       [ 0.209728  ],
       [ 0.88742794]])